### PR TITLE
Allow enforcing a re-login with OIDC provider

### PR DESCRIPTION
**Pull request by soxofaan**
PR for https://github.com/openEOPlatform/architecture-docs/issues/337 to allow enforcing a re-login through URL parameter

### CODE REVIEW

**Review by m-mohr — CHANGES_REQUESTED** [review]
Please set the prompt parameter in `created()`:

```js
// Allow enforcing a re-login with 'prompt=login' parameter on authentication request (https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).
let prompt = Utils.param('oidc~prompt');
if (['none', 'login', 'consent', 'select_account'].includes(prompt)) {
  this.oidcOptions.prompt = prompt;
}
```

Please add documentation for the parameter to the Readme:
https://github.com/Open-EO/openeo-web-editor#query-parameters

I changed the name so that in the future we could also easily add other OIDC parameter similarly.

**Comment by soxofaan** [comment]
great, thanks for the feedback

> oidc~prompt

I'm going to assume you just meant `oidc-prompt`, or is that tilde intended?

**Comment by m-mohr** [comment]
Tilde is intentional :-) Tilde is for a group of options in the Web Editor (such as in `wizard~`), assuming we could have more oidc~ options in the future.

**Comment by soxofaan** [comment]
Addressed the review notes.

Not necessarily for this PR: would it also be possible/feasible to automatically add this `prompt` parameter when the web editor receives catches a `PermissionsInsufficient` error, e.g. as a one-time fallback mechanism?

**Review by m-mohr — APPROVED** [review]

**Pull request merged**
