### PR TITLE
Add GHA for docker

### PR DESCRIPTION
**Pull request by mmacata**
This PR adds a github action to build and push the Dockerimage from this repository to Dockerhub. It contains a workflow which runs for push to master branch and creation of releases.

- for master branch it will create a docker image with tag containing sha-ref (e.g. sha-ad132f5)
- for releases it will create a docker image with tag latest
- for releases it will create a docker image with tag containing the released version (e.g. 1.2.3)

For this workflow to work, credentials to dockerhub are needed. In [the repository settings](https://github.com/Open-EO/openeo-web-editor/settings/secrets/actions) the secrets DOCKERHUB_TOKEN and DOCKERHUB_USERNAME would need to be created. For the values I would be willing to store mine (mmacata) or these of a machine user we use (mundialisdev) so no extra setup would be required but if it suits better, a new / different user can be created of course. The user is shown in Dockerhub, like it can be seen [here](https://hub.docker.com/repository/docker/mundialis/openeo-web-editor/tags?page=1&ordering=last_updated) for tag `sha-2da70e0`.

As docker repository, I used mundialis/openeo-web-editor, as this was the repository which had autobuild set up before and appeared in the checks for commits / pull requests in the past and I have access to. On Dockerhub I found no gerneral openeo organization but [`openeor`](https://hub.docker.com/u/openeor) and [`openeobs`](https://hub.docker.com/u/openeobs). `openeor` looks like specific to `r` Code and `openeobs` was updated last 3 years ago. So here - as well as with credentials - if it suits better, another repository can be used but I don't know which would fit. It is also possible to create an `openeo` organization on Dockerhub, if other repositories from openeo will benefit from it as well!?

I marked this PR as draft until the question about credentials is solved. Before any are added, this check would fail and should therefore not be merged.

### CODE REVIEW

**Comment by mmacata** [comment]
Ok, then I leave it with `mundialis/openeo-web-editor` and use the more general `mundialisdev` for creation. I have enough permissions, so I could add the secrets myself. Dockerhub organisation and user can of course be changed anytime if it should fit better, but currently it is the easiest to maintain for me.

Draft status is therefore resolved, please approve if I should merge.

**Review by m-mohr — APPROVED** [review]
Thanks. Please merge once config has been correctly set.

**Comment by m-mohr** [comment]
Thanks, I forgot: Could you add a chapter about this to the README? That says that there's a Docker image for this, where to find it, how to get started with it, and that you/mundialis maintains it? @mmacata

**Comment by mmacata** [comment]
Yes I will. First run was successful:

- action finished: https://github.com/Open-EO/openeo-web-editor/runs/3494245970?check_suite_focus=true
- image was pushed:  https://hub.docker.com/repository/docker/mundialis/openeo-web-editor/tags?page=1&ordering=last_updated

**Comment by mmacata** [comment]
README is updated. Please check if this is fine for you and modify (or tell me) if needed.

**Comment by m-mohr** [comment]
Thanks, that's all good!

**Pull request merged**
